import { parseEbnf } from "@/lib/parser-lab";
import type { EbnfGrammar } from "@/lib/parser-lab";

export type CodeExportSettings = {
  caseSensitive: boolean;
  errorFormat: "detailed" | "compact";
  includeCli: boolean;
  includeComments: boolean;
  includeExample: boolean;
  includeParseTree: boolean;
  includeTrace: boolean;
  inputMode: "tokens" | "characters";
  maxRepeatIterations: number;
  moduleFormat: "standalone" | "commonjs" | "esm";
  parserName: string;
  skipWhitespace: boolean;
  startRule: string;
  strictEnd: boolean;
  strategy: "recursive-descent";
};

export const DEFAULT_CODE_EXPORT_SETTINGS: CodeExportSettings = {
  caseSensitive: true,
  errorFormat: "detailed",
  includeCli: true,
  includeComments: true,
  includeExample: true,
  includeParseTree: true,
  includeTrace: false,
  inputMode: "tokens",
  maxRepeatIterations: 1000,
  moduleFormat: "standalone",
  parserName: "GeneratedParser",
  skipWhitespace: true,
  startRule: "",
  strictEnd: true,
  strategy: "recursive-descent",
};

export function exportParserCode(
  grammarText: string,
  settings: CodeExportSettings,
) {
  const code = generateParserCode(grammarText, settings);
  const extension = settings.moduleFormat === "esm" ? "mjs" : "js";
  const fileName = `${slugify(settings.parserName) || "generated-parser"}.${extension}`;
  downloadTextFile(fileName, code);
}

export function generateParserCode(
  grammarText: string,
  settings: CodeExportSettings,
) {
  const grammar = parseEbnf(grammarText);
  const startRule = grammar.nonTerminals.includes(settings.startRule)
    ? settings.startRule
    : grammar.start;
  const parserName = safeIdentifier(settings.parserName, "GeneratedParser");
  const runtimeOptions = {
    caseSensitive: settings.caseSensitive,
    errorFormat: settings.errorFormat,
    includeParseTree: settings.includeParseTree,
    includeTrace: settings.includeTrace,
    inputMode: settings.inputMode,
    maxRepeatIterations: settings.maxRepeatIterations,
    skipWhitespace: settings.skipWhitespace,
    startRule,
    strictEnd: settings.strictEnd,
  };
  const generatedAt = settings.includeComments
    ? [
        "/*",
        " * Generated by The Ultimate Parser.",
        " * Strategy: deterministic recursive descent with ordered alternatives.",
        " * Edit the grammar object below to change the accepted language.",
        " */",
        "",
      ].join("\n")
    : "";

  return [
    generatedAt,
    `"use strict";`,
    "",
    `const grammar = ${stableJson(normalizeGrammar(grammar, startRule))};`,
    "",
    `const defaultOptions = ${stableJson(runtimeOptions)};`,
    "",
    parserRuntime(parserName),
    settings.includeExample ? exampleSnippet(parserName, settings) : "",
    moduleSnippet(parserName, settings.moduleFormat),
    settings.includeCli ? cliSnippet(parserName, settings.moduleFormat) : "",
  ]
    .filter(Boolean)
    .join("\n");
}

function normalizeGrammar(grammar: EbnfGrammar, startRule: string) {
  return {
    start: startRule,
    nonTerminals: grammar.nonTerminals,
    terminals: grammar.terminals,
    rules: grammar.rules,
  };
}

function parserRuntime(parserName: string) {
  return `class ${parserName} {
  constructor(options = {}) {
    this.options = { ...defaultOptions, ...options };
    this.ruleMap = new Map(grammar.rules.map((rule) => [rule.lhs, rule]));
    this.nonTerminals = new Set(grammar.nonTerminals);
    this.trace = [];
    this.bestError = null;
    this.source = "";
  }

  parse(input, startRule = this.options.startRule || grammar.start) {
    this.trace = [];
    this.bestError = null;
    this.source = String(input ?? "");
    const stream = this.options.inputMode === "characters" ? this.source : this.tokenize(this.source);
    const result = this.parseRule(startRule, 0, stream);
    const endIndex = this.options.inputMode === "characters" ? this.skipIgnored(result.index, stream) : result.index;
    const accepted = result.ok && (!this.options.strictEnd || endIndex === stream.length);

    if (!accepted && result.ok && this.options.strictEnd) {
      this.recordError(endIndex, "end of input");
    }

    const output = {
      ok: accepted,
      nextIndex: accepted ? endIndex : result.index,
    };

    if (this.options.includeParseTree) output.tree = accepted ? result.node : null;
    if (this.options.includeTrace) output.trace = this.trace.slice();
    if (!accepted) output.error = this.formatError();

    return output;
  }

  tokenize(input) {
    return input.trim() ? input.trim().split(/\\s+/) : [];
  }

  parseRule(ruleName, index, stream) {
    const rule = this.ruleMap.get(ruleName);
    if (!rule) return this.fail(index, ruleName);

    this.traceStep("enter", ruleName, index);

    for (const alternative of rule.alternatives) {
      const result = this.parseSequence(alternative, index, stream);
      if (result.ok) {
        const node = { type: "rule", name: ruleName, children: result.nodes };
        this.traceStep("exit", ruleName, result.index);
        return { ok: true, index: result.index, node };
      }
    }

    this.traceStep("fail", ruleName, index);
    return this.fail(index, ruleName);
  }

  parseSequence(sequence, index, stream) {
    const nodes = [];
    let cursor = index;

    for (const term of sequence) {
      const result = this.parseTerm(term, cursor, stream);
      if (!result.ok) return result;
      cursor = result.index;
      if (result.node) nodes.push(result.node);
    }

    return { ok: true, index: cursor, nodes };
  }

  parseTerm(term, index, stream) {
    if (term.kind === "symbol") {
      return this.nonTerminals.has(term.value)
        ? this.parseRule(term.value, index, stream)
        : this.matchTerminal(term.value, index, stream);
    }

    if (term.kind === "group") {
      return this.parseAlternatives(term.alternatives, index, stream, "group");
    }

    if (term.kind === "optional") {
      const result = this.parseAlternatives(term.alternatives, index, stream, "optional");
      return result.ok ? result : { ok: true, index, node: { type: "optional", children: [] } };
    }

    const children = [];
    let cursor = index;

    for (let count = 0; count < this.options.maxRepeatIterations; count += 1) {
      const result = this.parseAlternatives(term.alternatives, cursor, stream, "repeat");
      if (!result.ok || result.index === cursor) break;
      cursor = result.index;
      if (result.node) children.push(result.node);
    }

    return { ok: true, index: cursor, node: { type: "repeat", children } };
  }

  parseAlternatives(alternatives, index, stream, type) {
    for (const alternative of alternatives) {
      const result = this.parseSequence(alternative, index, stream);
      if (result.ok) {
        return { ok: true, index: result.index, node: { type, children: result.nodes } };
      }
    }

    return this.fail(index, type);
  }

  matchTerminal(expected, index, stream) {
    if (this.options.inputMode === "characters") {
      const cursor = this.skipIgnored(index, stream);
      const actual = stream.slice(cursor, cursor + expected.length);
      if (this.same(actual, expected)) {
        return {
          ok: true,
          index: cursor + expected.length,
          node: { type: "token", value: actual },
        };
      }
      return this.fail(cursor, expected);
    }

    const actual = stream[index];
    if (actual !== undefined && this.same(actual, expected)) {
      return {
        ok: true,
        index: index + 1,
        node: { type: "token", value: actual },
      };
    }
    return this.fail(index, expected);
  }

  skipIgnored(index, stream) {
    if (this.options.inputMode !== "characters" || !this.options.skipWhitespace) return index;
    let cursor = index;
    while (cursor < stream.length && /\\s/.test(stream[cursor])) cursor += 1;
    return cursor;
  }

  same(actual, expected) {
    if (this.options.caseSensitive) return actual === expected;
    return String(actual).toLowerCase() === String(expected).toLowerCase();
  }

  fail(index, expected) {
    this.recordError(index, expected);
    return { ok: false, index };
  }

  recordError(index, expected) {
    if (!this.bestError || index >= this.bestError.index) {
      this.bestError = { index, expected };
    }
  }

  formatError() {
    if (!this.bestError) return "Input was rejected.";
    if (this.options.errorFormat === "compact") return \`Expected \${this.bestError.expected}\`;
    return \`Expected \${this.bestError.expected} at \${this.positionLabel(this.bestError.index)}.\`;
  }

  positionLabel(index) {
    return this.options.inputMode === "characters" ? \`character \${index}\` : \`token \${index}\`;
  }

  traceStep(action, subject, index) {
    if (!this.options.includeTrace) return;
    this.trace.push({ action, subject, index });
  }
}`;
}

function exampleSnippet(parserName: string, settings: CodeExportSettings) {
  const exampleInput =
    settings.inputMode === "characters"
      ? "replace this string"
      : "replace these tokens";

  return `\n// Example:
// const parser = new ${parserName}();
// const result = parser.parse(${JSON.stringify(exampleInput)});
// console.log(JSON.stringify(result, null, 2));`;
}

function moduleSnippet(
  parserName: string,
  moduleFormat: CodeExportSettings["moduleFormat"],
) {
  if (moduleFormat === "commonjs") {
    return `\nmodule.exports = { ${parserName}, grammar };`;
  }

  if (moduleFormat === "esm") {
    return `\nexport { ${parserName}, grammar };`;
  }

  return "";
}

function cliSnippet(
  parserName: string,
  moduleFormat: CodeExportSettings["moduleFormat"],
) {
  const body = `const parser = new ${parserName}();
  const input = process.argv.slice(2).join(" ");
  const result = parser.parse(input);
  console.log(JSON.stringify(result, null, 2));
  process.exitCode = result.ok ? 0 : 1;`;

  if (moduleFormat === "esm") {
    return `\nif (typeof process !== "undefined" && import.meta.url === \`file://\${process.argv[1]}\`) {
  ${body}
}`;
  }

  if (moduleFormat === "commonjs") {
    return `\nif (typeof require !== "undefined" && require.main === module) {
  ${body}
}`;
  }

  return `\nif (typeof process !== "undefined" && process.argv && process.argv[1]) {
  ${body}
}`;
}

function stableJson(value: unknown) {
  return JSON.stringify(value, objectKeySorter, 2);
}

function objectKeySorter(_key: string, value: unknown) {
  if (!value || Array.isArray(value) || typeof value !== "object") return value;

  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>).sort(([left], [right]) =>
      left.localeCompare(right),
    ),
  );
}

function safeIdentifier(value: string, fallback: string) {
  const cleaned = value.replace(/[^A-Za-z0-9_$]/g, "");
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(cleaned)) return cleaned;
  return fallback;
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function downloadTextFile(fileName: string, content: string) {
  const blob = new Blob([content], { type: "text/javascript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(url);
}
